import numpy as np

# 1.1 3x3 Identity Matrix I
I = np.array([[1,0,0], 
              [0,1,0], 
              [0,0,1]])
print("The Matrix I =\n", I)

#1.2 3x3 Matrix B
B = np.array([[2,2,0],
              [3,0,3],
              [1,0,5]])
print("\nThe Matrix B =\n", B)

#1.3 3x3 Matrix C
C = I-B
print("\nThe Matrix C =\n", C)

#1.4 3x1 Vector D
d = np.array([[40],[60],[80]])
print("\nThe Vector d =\n", d)

#1.5i Determinant of C
detC = np.linalg.det(C)
print("\nThe Determinant of Matrix C =\n", detC)

#1.5ii Eigenvalues of C
evaC, eveC = np.linalg.eig(C)
print("\nThe Eigenvalues of Matrix C are\n", evaC)

#1.5iii Eigenvectors of C
print("\nThe Eigenvectors of Matrix C are\n", eveC)

#1.6 Inverse of C
print("\nThe inverse of C must exist because in #1.5i, we calculated the determinant of C and it was nonzero. "
      "This proof works by the Invertible Matrix Theorem.\n"
      "We can also prove this relationship by analyzing Cramer's Rule: where the inverse of the matrix C is found by the adjoint of C divided by the determinant of C.\n"
      "The adjoint (being the numerator) can take on any value; however, if the determinant is 0, the inverse will be undefined and thus won't exist.\n"
      "Because our matrix C has a nonzero determinant, its inverse must exist.")
Cinv = np.linalg.inv(C)
print("The Inverse of Matrix C =\n", Cinv)

#1.7i Cx=d via inverse
xinv = np.dot(Cinv, d)
print("\nThe Solution Vector x via the Inverse =\n", xinv)

#1.7ii Cx=d via solve function
xsolve = np.linalg.solve(C,d)
print("\nThe Solution Vector x via the Solve Function =\n", xsolve)

#1.8 SVD Factorization using C to get U Σ and V
U, Σ1d, VT = np.linalg.svd(C)
print("\nThe Matrix U =\n", U)
print("\nThe Matrix Σ =\n", np.diag(Σ1d))
print("\nThe Matrix V =\n", np.transpose(VT))

#1.9 Products of U, UT and V, VT
V = np.transpose(VT)
UT = np.transpose(U)
print("\nThe Transpose of U multiplied by U is\n", np.dot(UT, U))
print("\nU multiplied by the transpose of U is\n", np.dot(U, UT))
print("The transpose of U is effectively the inverse of U.\n" 
      "This is because the transpose of U multiplied by U has almost exactly 1 on the\n" 
      "diagonals while having approximately 0 as every other entry.\n"
      "Also when U is multiplied by the transpose of U, the resulting matrix has almost\n" 
      "exactly 1 on the diagonals while having approximately 0 as every other entry.\n"
      "U multiplied by the transpose of U approximately equals the identity matrix.\n")
print("\nThe Transpose of V multiplied by V is\n", np.dot(VT, V))
print("\nV multiplied by the transpose of V is\n", np.dot(V, VT))
print("The transpose of V is effectively the inverse of V.\n" 
      "This is because the transpose of V multiplied by V has almost exactly 1 on the\n" 
      "diagonals while having approximately 0 as every other entry.\n"
      "Also when U is multiplied by the transpose of U, the resulting matrix has almost\n" 
      "exactly 1 on the diagonals while having approximately 0 as every other entry.\n"
      "V multiplied by the transpose of V approximately equals the identity matrix.")

#1.10 x via U, Σ, V, d
Σ = np.diag(Σ1d)
temp1 = np.dot(V, np.linalg.inv(Σ))
temp2 = np.dot(temp1, UT)
xsvd =  np.dot(temp2, d)
print("\n The Solution Vector x via the SVD =\n", xsvd)

#2.1 4x3 Matrix A and 4x1 Vector b
A = np.array([[1,3,5], 
              [1,1,0], 
              [1,1,2], 
              [1,3,3]])
print("\nThe Matrix A =\n", A)
b = np.array([[3],
              [5],
              [7],
              [-3]])
print("\nThe Vector b =\n", b)

#2.2 3x1 Vector s via ATb
AT = np.transpose(A)
s = np.dot(AT, b)
print("\nThe Vector s =\n", s)

#2.2 3x3 Matrix E via (ATA)^-1
temp1 = np.dot(AT, A)
E = np.linalg.inv(temp1)
print("\nThe Matrix E =\n", E)

#2.3 Solving for x via Es
xEs = np.dot(E, s)
print("\nThe vector x generated by E and s =\n", xEs)

#2.4 Solving for norm of b-Ax using Normal Equations
temp1 = np.dot(A, xEs)
temp2 = b - temp1
normNE = np.linalg.norm(temp2)
print("\nThe norm of b-Ax =\n", normNE)

#2.5 Q and R from QR Factorization
Q, R = np.linalg.qr(A)
print("\nThe Matrix Q =\n", Q)
print("\nThe Matrix R =\n", R)

#2.6 Solve for x via Q, R, b
temp1 = np.dot(np.linalg.inv(R), np.transpose(Q))
xQR = np.dot(temp1, b)
print("\nThe vector x generated by the Inverse of Q, the Transpose of R, and b =\n", xQR)

#2.7 Solving for norm of b-Ax using QR Factorization
temp1 = np.dot(A, xQR)
temp2 = b - temp1
normQR = np.linalg.norm(temp2)
print("\nThe norm of b-Ax =\n", normQR)